spring.application.name=crudSpringBoot
# 1. JDBC Connection URL (Format: jdbc:database_type://host:port/database_name)
spring.datasource.url=jdbc:mysql://localhost:3306/student_database?useSSL=false&serverTimezone=UTC

# 2. Database Credentials
spring.datasource.username=root
spring.datasource.password=kanugoli@2072

# 3. JDBC Driver Class
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 4. JPA / Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect